[package]
name = "hello-ggez"
version = "0.1.0"
authors = ["NeuroWhAI <tlsehdgus0212@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
gfx_core = "0.9"
gfx_device_gl = "0.16"
imgui = "0.1"
imgui-gfx-renderer = "0.1"
imgui-winit-support = "0.1"